### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Jeimy041** [hoilo23/AutoAccept#1]
Hello, I´ve got a question, my question is about this software.
Is this software injecting onto the game?
If is not injecting does it read/write memory?
And can this lead into a ban'
Thank you, and kep on the good work!

**Comment by hoilo23** [comment]
Hi, It's not injecting into the game. The only thing it is doing is checking a pixel for a certain color (To look for an accept button, for example.), moving your mouse, and clicking.

**Comment by Jeimy041** [comment]
Thank you
